export { default as udaan } from './pic/udaan.jpg'
export { default as black } from './pic/black.jpg'
export { default as avatar} from './pic/avatar.jpg'
export { default as  devdas} from './pic/devdas.jpg'
export { default as  baahubali} from './pic/baahubali.jpg'
export { default as  white} from './pic/white.jpg'